# Generated by Django 5.2.17 on 2026-09-02 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('goal_type', models.CharField(choices=[('TIME_BOUND', 'Time-bound'), ('ONGOING', 'Ongoing')], default='TIME_BOUND', max_length=15)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('initial_estimate_level', models.IntegerField(default=1, help_text="User's self-assessed initial skill level (1-10)")),
                ('assessment_data', models.JSONField(blank=True, default=dict, help_text='Dynamic Q&A answers used by AI to generate the roadmap')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
