# Generated by Django 5.2.17 on 2026-09-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_roadmapphase_roadmapobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
