# Generated by Django 4.2.30 on 2026-09-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_progress_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='daily_target_hours',
            field=models.FloatField(default=2.0, help_text='Target hours per day to spend on this goal'),
        ),
    ]
