# Generated by Django 5.2.17 on 2026-09-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_is_completed_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notify',
            field=models.BooleanField(default=False, help_text='User opted in to notifications'),
        ),
    ]
