# Generated by Django 5.2.17 on 2026-09-02 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EverydayActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BRUSHING', 'Brushing'), ('BATHING', 'Bathing'), ('MORNING_ROUTINE', 'Morning Routine'), ('EVENING_ROUTINE', 'Evening Routine'), ('PERSONAL_CARE', 'Personal Care'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('preferred_time', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='everyday_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FixedCommitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('WORK', 'Work'), ('COLLEGE', 'College'), ('SCHOOL', 'School'), ('MEALS', 'Meals'), ('TRAVEL', 'Travel'), ('APPOINTMENTS', 'Appointments'), ('FAMILY', 'Family'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.CharField(default='0,1,2,3,4,5,6', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_commitments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
