# Generated by Django 5.2.17 on 2026-09-02 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('block_type', models.CharField(choices=[('FIXED', 'Fixed Commitment'), ('EVERYDAY', 'Everyday Activity'), ('TASK', 'Goal Task'), ('SLEEP', 'Sleep'), ('BREAK', 'Break')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('everyday_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.everydayactivity')),
                ('fixed_commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.fixedcommitment')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='scheduling.dailyschedule')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
