# Generated by Django 5.2.17 on 2026-09-02 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_dailyschedule_scheduleblock'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyschedule',
            unique_together={('user', 'date')},
        ),
    ]
