# Generated by Django 4.2.30 on 2026-09-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_scheduleblock_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='warning_message',
            field=models.TextField(blank=True, help_text="AI warning if schedule couldn't fit target hours", null=True),
        ),
    ]
