# Generated by Django 4.2.30 on 2026-09-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_dailyschedule_warning_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
